# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on: push


jobs:
  check-hw:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 2.7
    - uses: actions/checkout@main
      with:
        repository: MultiRobotControl/hw_checker
    - name: ls
      run: ls -la
      shell: bash
    - name: Display Python version
      run: python -c "import sys; print(sys.version)"
    