# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on: push


jobs:
  check-hw:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout this repo.
      uses: actions/checkout@v2
      with:
        path: ay21_hw1
    - name: Checkout testing scripts
      uses: actions/checkout@v2
      with:
        repository: MultiRobotControl/hw_checker
        path: hw_checker
        ref: main
    - name: Set up Python 2.7
      uses: actions/setup-python@v2
      with:
        python-version: 2.7
    #- name: ls
    #  run: |
    #    ls -la hw
    #    ls -la hw_checker
    #  shell: bash
    - name: Run python hw checker
      run: |
        cd ./hw_checker
        python hw1_test.py
    